### ISSUE TITLE
module installs perfectly, but when ran backup doesnt create files

### ISSUE THREAD

**Issue by joolsr** [Yenthe666/auto_backup#25] opened 2015-12-22 09:50 UTC
Hi

I used your install script for odoo 9 so odoo is running under the odoo user. Installing with Ubuntu 64 bit server 14.04 was straight forward, but even though everything with the module installed perfectly, and I see this sensible entry in the odoo log when I run the backup from the scheduler :-

ie 2015-12-16 16:42:53,293 3400 INFO None openerp.service.db: DUMP DB: elite format zip

the folder is created, everything appears fine but never are any backup files created.

I’m happy to help debug if you can help by supplying screenshots etc and config

It could be a permissions issue, but even setting 777 privs on the folder does not help. I tried changing the odoo log to debug but no further useful info was provided.

**Comment by Yenthe666** [comment] 2015-12-22 09:52
@joolsr,

Can you post a screen of your configuration please? (blank out the credentials good enough)

**Comment by joolsr** [comment] 2015-12-22 13:18
Its only using the filesystem not ftp which is why its odd its not working ..

That said i'm using ssl and redirection (so 8069 isnt available externally) which i guess means that the backup can reach port 8069 locally, or does it ?

![backup-error](https://cloud.githubusercontent.com/assets/934876/11955954/44f1ec3a-a8ae-11e5-9eb1-5537af430c38.jpg)

**Comment by Yenthe666** [comment] 2015-12-22 13:29
@joolsr,

I'm actually going to guess that it can't reach the Odoo due to the SSL/redirection. The thing is that this'll be realllyyyyyy hard to debug since this is probably something from outside Odoo that is blocking it. You could try to put everything open and remove the HTTPS for a bit, just to check if it comes from there.

**Comment by joolsr** [comment] 2015-12-22 13:30
I could run a netstat -pntl to see if there is anything listening on that port .. ?

**Comment by Yenthe666** [comment] 2015-12-22 13:50
Always worth a try as a starter!

**Comment by joolsr** [comment] 2015-12-23 09:52
running netstat -pntl on the inside of the box does show that port 8069 is listening

tcp        0      0 0.0.0.0:8069            0.0.0.0:*               LISTEN      18420/python

**Comment by joolsr** [comment] 2015-12-23 09:53
would be good to fix, as obviously its much better to run any web service https these days ..

**Comment by joolsr** [comment] 2016-01-02 20:23
ok, running odoo in Debug mode explains a bit more about the problem ..

2016-01-02 20:17:46,870 32341 DEBUG elite openerp.addons.auto_backup.backup_scheduler: Couldn't backup database xxxx. Bad database administrator password for server running at http://localhost:8069

I guess this is the the db password in the main odoo config file. What might be the issue is that I used your script ie http://www.odoo.yenthevg.com/installing-odoo-9-on-ubuntu-14-04/ and I believe because of the way that the odoo user is setup to run odoo that it doesn't use a 'normal' database password (ie runs password less when connecting to postgres), or at least I don't remember seeing/or choosing one at the time...

Can you help ?

**Comment by Yenthe666** [comment] 2016-01-04 07:00
@joolsr the database password can be different from the one in your config file. I use my script all the time and the back-ups work just fine, so you must have something else wrong..

**Comment by CedesaIngenieria** [comment] 2016-01-07 19:01
Hello!!

I have the same Issue. I put the same password in both places, file and db manager. Any ideas?

Here is my log

016-01-07 18:55:41,873 1540 INFO Cedesa werkzeug: 80.58.167.230 - - [07/Jan/2016 18:55:41] "POST /longpolling/poll HTTP/1.1" 200 -
2016-01-07 18:55:55,873 1540 INFO Cedesa werkzeug: 88.10.219.44 - - [07/Jan/2016 18:55:55] "POST /longpolling/poll HTTP/1.1" 200 -
2016-01-07 18:56:09,062 1540 INFO Cedesa werkzeug: 47.62.102.224 - - [07/Jan/2016 18:56:09] "POST /longpolling/poll HTTP/1.1" 200 -
2016-01-07 18:56:32,122 1540 INFO Cedesa werkzeug: 80.58.167.230 - - [07/Jan/2016 18:56:32] "POST /longpolling/poll HTTP/1.1" 200 -
2016-01-07 18:56:46,036 1540 INFO Cedesa werkzeug: 88.10.219.44 - - [07/Jan/2016 18:56:46] "POST /longpolling/poll HTTP/1.1" 200 -
2016-01-07 18:56:59,162 1540 INFO Cedesa werkzeug: 47.62.102.224 - - [07/Jan/2016 18:56:59] "POST /longpolling/poll HTTP/1.1" 200 -
2016-01-07 18:57:00,655 1540 INFO None werkzeug: 51.254.99.86 - - [07/Jan/2016 18:57:00] "POST /xmlrpc/db HTTP/1.1" 200 -
2016-01-07 18:57:00,659 1540 INFO None openerp.service.db: DUMP DB: Cedesa format zip
2016-01-07 18:57:14,378 1540 INFO None werkzeug: 51.254.99.86 - - [07/Jan/2016 18:57:14] "POST /xmlrpc/db HTTP/1.1" 200 -
2016-01-07 18:57:17,808 1540 ERROR Cedesa openerp.addons.base.ir.ir_cron: Call of self.pool.get('db.backup').schedule_backup(cr, uid, *()) failed in Job 13
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_cron.py", line 138, in _callback
    getattr(model, method_name)(cr, uid, *args)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 256, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/auto_backup/backup_scheduler.py", line 156, in schedule_backup
    logger.notifyChannel('backup', netsvc.LOG_INFO, "Couldn't backup database %s. Bad database administrator password for server running at http://%s:%s" %(rec.name, rec.host, rec.port))
NameError: global name 'logger' is not defined

Thank you!!

**Comment by joolsr** [comment] 2016-01-07 21:12
Hi

I run mine multiworker with longpolling too. I read a post last night that
sometime used a config in same situation of port 8072 instead of the usual
8069 to poll the longpolling port which worked for them but I don't know
why ..

I still can't get past the same admin password error unfortunately

I really want to get this working so I'm happy to help debug this

Julian

**Comment by Yenthe666** [comment] 2016-01-08 14:12
@CedesaIngenieria are you running some form of multiworker too? I really have no clue where this error is coming from, you guys seem to be the first having this..

**Comment by CedesaIngenieria** [comment] 2016-01-09 15:19
No, Just default configuration, with worker = 0 on my config.py. Thank you

**Comment by lisandi** [comment] 2016-01-19 08:34
Hi Yenthe I can verify that problem
also we are running the site over an apache proxy on https://

None openerp.service.db: DUMP DB
is the error in the log.

Port 8069 or 8072 with same problem. No files get created no db backup be done.

**Comment by Yenthe666** [comment] 2016-01-19 11:33
@lisandi the problem is either going to be with the proxy or the https:/ I assume.
I never use those so I can't debug this.. could you give it a try please?

**Comment by CedesaIngenieria** [comment] 2016-01-22 09:02
Hello,

It isn't a https bug. I have it on http.

Thank you!

**Comment by joolsr** [comment] 2016-02-04 15:56
I still cant get this to operate unfortunately, although the reason is still unknown. I may have to try another backup script instead :-(

**Comment by Yenthe666** [comment] 2016-02-06 12:01
@joolsr sorry but I have no way at all to reproduce this issue and I just have too little information to fix this I'm afraid..

**Comment by joolsr** [comment] 2016-02-06 15:10
Ok understood.

Its annoying in these circumstances for all .. I'm happy to run some
diagnostics if you have some ideas on what to look for.

Julian

**Comment by Yenthe666** [comment] 2016-02-06 15:45
@joolsr have a look at the password under `/etc/odoo-server.conf` and see if it matches with the one you used. If this doesn't match it comes from there, if it does I'd try to overwrite all your password everywhere and make them all the same. I know its a hassle and a far fetch but I'm not sure about another fix..

**Comment by gary-no-1** [comment] 2016-02-11 12:16
scheduled auto backup stopped working since 9th feb. uninstalled and re-installed the module but of no use. same error as noted above - 
```
 Call of self.pool.get('db.backup').schedule_backup(cr, uid, ()) failed in Job 13
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_cron.py", line 138, in _callback
getattr(model, method_name)(cr, uid, *args)
File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 256, in wrapper
return old_api(self, *args, *kwargs)
File "/usr/lib/python2.7/dist-packages/openerp/addons/auto_backup/backup_scheduler.py", line 156, in schedule_backup
logger.notifyChannel('backup', netsvc.LOG_INFO, "Couldn't backup database %s. Bad database administrator password for server running at http://%s:%s" %(rec.name, rec.host, rec.port))
NameError: global name 'logger' is not defined
```
using odoo v8. no change in database passwords. foxed !!

**Comment by CedesaIngenieria** [comment] 2016-02-15 10:44
What is the fix for this? Passwords? Thank you!





*Ingeniería e Innovación TIC *

Oficina: Extremadura 924 09 06 08
C/ Jacinta García Hernández  13A. Oficina 9-12. Badajoz

www.cedesa.es <https://mail.google.com/>


[image: Facebook] <http://facebook.com/cedesaingenieria> [image: Twitter]
<http://twitter.com/cedesaing> [image: Google Plus]
<http://google.com/cedesaesperitosinformaticos> [image: Youtube]

AVISO SOBRE CONFIDENCIALIDAD: Este documento se dirige exclusivamente a su
destinatario. Puede contener información confidencial sometida a secreto
profesional y su divulgación está prohibida en virtud de la legislación
vigente, se informa que si no es usted el destinatario o la persona
autorizada por el mismo, que la información contenida en este mensaje es
reservada y su utilización o divulgación con cualquier fin está prohibida.
Si ha recibido este documento por error, le rogamos que nos lo comunique
por teléfono, o e-mail y proceda a su destrucción. En el envío de e-mail no
se puede garantizar la seguridad ya que esta información puede ser
modificada, interceptada, o incompleta. El remitente no acepta
responsabilidad por los errores u omisiones en el contenido o anexos de
este e-mail. Se le informa que de la responsabilidad de un fichero de datos
de carácter personal, denominado CLIENTES, cuya finalidad es la relación
comercial, y el envío de documentación. Le informamos que podrá ejercer los
derechos de acceso, rectificación, cancelación u oposición en la dirección
indicada mediante escrito, concretando su solicitud y al que acompañe
fotocopia de su Documento Nacional de Identidad. El envío de este e-mail
responde con la totalidad de la legislación vigente. Ley Orgánica de
Protección de Datos y Ley de Servicios de la Sociedad de la Información,
igualmente si no desea recibir más información de nuestra empresa, mándenos
un e-mail con la palabra “baja” en el apartado asunto.


2016-02-11 13:16 GMT+01:00 gary-no-1 <notifications@github.com>:

**Comment by Yenthe666** [comment] 2016-03-15 07:21
I'm closing this since I have no way to reproduce this, sorry guys..

**Closed** 2016-03-15 07:21 UTC

**Comment by Paddue** [comment] 2016-04-12 13:08
Hey, in my case i get a MemoryError() from `bkp = execute(conn, 'dump', tools.config['admin_passwd'], rec.name)`. The error occurs, after  
> DUMP DB successful: my_database
is written in the log. In this case the memory get constantly filled until ~ 40-60 mb left in a 4 gb linux system.

**Comment by Yenthe666** [comment] 2016-04-12 13:47
@Paddue thanks for providing some more information. So in essence this dump function is filling up the RAM until your server is out and then it'll stop?
Which Odoo version do you run and is it community or enterprise?

**Comment by Paddue** [comment] 2016-04-12 14:30
@Yenthe666 thats the point^^
i'm working with Odoo v8

**Comment by temis0506** [comment] 2019-03-20 20:22
I have a similar problem. I use odoo 8 that run on bitnami on a mac, but the module, despite being configured according to the specifications, does not generate any files, as I was checking in the bitnami logs it says something like it has problems with the daemon but not how to fix it . greetings and waiting for your help

**Comment by AntMoreno** [comment] 2019-04-19 10:07
In my case the addon was working perfectly fine (v8) until the DB size reached around 220Mb, when the addon stopped working with the following error:

_logger.notifyChannel('backup', netsvc.LOG_INFO, "Couldn't backup database %s. Bad database administrator password for server running at http://%s:%s" %(rec.name, rec.host, rec.port))
NameError: global name 'logger' is not defined_

The thing is that if I try to backup another DB in the same server it works perfectly fine. It works also in a restored backup of the production DB from a couple of months ago, but doesn't in the actual production database. So to test if there was something not properly setup in the current production DB I duplicated it, removed some info (attachments, non confirmed quotations and orders,...) just to downsize the DB to ~200Mb, and it has worked again. So definitely is something related to the size of the DB despite the apparent authentication problem that the log shows.

As backups are a critical issue I am going to move to the classical DB DUMP scripts, but it is a pity that such a useful addon has this glitch that makes it only valid for small sized DBs.

Please, if anyone ever finds a workaround post it here, I prefer to manage DB backups from the Odoo interface since it allows users to do so, not depending on IT people to create and admin them.

Thank you. best regards

**Comment by Yenthe666** [comment] 2019-04-19 10:18
@AntMoreno hmm interesting I haven't heard this feedback yet. Have you checked if your server is not closing off the connection before the backup is done? For example because of timeouts on Nginx requests, CPU processes, SSH connections, ..
Note: I backup databases over 3GB with this module.

**Comment by AntMoreno** [comment] 2019-04-19 11:10
Hi @Yenthe666, thank you for your prompt reply. This server doesn't have Nginx installed, and the only log I've checked is that of Odoo (sorry, I am not familiar with linux systems administration, if you can point me where to look I'll do so gladly).

This is what the  complete log while the backup is running looks like (scheduler was set to launch backup at 10:36:00):

_2019-04-19 10:35:50,341 1140 INFO SAMDB werkzeug: 174.56.29.47 - - [19/Apr/2019 10:35:50] "POST /longpolling/poll HTTP/1.1" 200 -
2019-04-19 10:36:40,587 1140 INFO SAMDB werkzeug: 174.56.29.47 - - [19/Apr/2019 10:36:40] "POST /longpolling/poll HTTP/1.1" 200 -
2019-04-19 10:36:53,444 1140 INFO None werkzeug: 127.0.0.1 - - [19/Apr/2019 10:36:53] "POST /xmlrpc/db HTTP/1.1" 200 -
2019-04-19 10:36:53,454 1140 INFO None openerp.service.db: DUMP DB: SAMDB format zip
2019-04-19 10:37:31,173 1140 INFO SAMDB werkzeug: 174.56.29.47 - - [19/Apr/2019 10:37:31] "POST /longpolling/poll HTTP/1.1" 200 -
2019-04-19 10:38:22,036 1140 INFO SAMDB werkzeug: 174.56.29.47 - - [19/Apr/2019 10:38:22] "POST /longpolling/poll HTTP/1.1" 200 -
2019-04-19 10:39:11,602 1140 INFO None werkzeug: 127.0.0.1 - - [19/Apr/2019 10:39:11] "POST /xmlrpc/db HTTP/1.1" 200 -
2019-04-19 10:39:12,251 1140 INFO SAMDB werkzeug: 174.56.29.47 - - [19/Apr/2019 10:39:12] "POST /longpolling/poll HTTP/1.1" 200 -
2019-04-19 10:39:27,211 1140 ERROR SAMDB openerp.addons.base.ir.ir_cron: Call of self.pool.get('db.backup').schedule_backup(cr, uid, *()) failed in Job 8
Traceback (most recent call last):
  File "/opt/odoo/openerp/addons/base/ir/ir_cron.py", line 138, in _callback
    getattr(model, method_name)(cr, uid, *args)
  File "/opt/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons_custom/auto_backup/backup_scheduler.py", line 156, in schedule_backup
    logger.notifyChannel('backup', netsvc.LOG_INFO, "Couldn't backup database %s. Bad database administrator password for server running at http://%s:%s" %(rec.name, rec.host, rec.port))
NameError: global name 'logger' is not defined
2019-04-19 10:40:02,440 1140 INFO SAMDB werkzeug: 174.56.29.47 - - [19/Apr/2019 10:40:02] "POST /longpolling/poll HTTP/1.1" 200 -__

In the duplicated DB (~195Mb)this is the log (launched at 10:59:00, ended succesfully at 11:01:48):

2019-04-19 10:58:51,227 4967 INFO SAMDB_TEST werkzeug: 174.56.29.47 - - [19/Apr/2019 10:58:51] "POST /web/menu/load_needaction HTTP/1.1" 200 -
2019-04-19 10:59:17,020 4967 INFO SAMDB_TEST werkzeug: 174.56.29.47 - - [19/Apr/2019 10:59:17] "POST /longpolling/poll HTTP/1.1" 200 -
2019-04-19 10:59:43,778 4967 INFO None werkzeug: 127.0.0.1 - - [19/Apr/2019 10:59:43] "POST /xmlrpc/db HTTP/1.1" 200 -
2019-04-19 10:59:43,780 4967 INFO None openerp.service.db: DUMP DB: SAMDB_TEST format zip
2019-04-19 11:00:07,175 4967 INFO SAMDB_TEST werkzeug: 174.56.29.47 - - [19/Apr/2019 11:00:07] "POST /longpolling/poll HTTP/1.1" 200 -
2019-04-19 11:00:57,960 4967 INFO SAMDB_TEST werkzeug: 174.56.29.47 - - [19/Apr/2019 11:00:57] "POST /longpolling/poll HTTP/1.1" 200 -
2019-04-19 11:01:22,470 4967 INFO None werkzeug: 127.0.0.1 - - [19/Apr/2019 11:01:22] "POST /xmlrpc/db HTTP/1.1" 200 -
2019-04-19 11:01:48,279 4967 INFO SAMDB_TEST werkzeug: 174.56.29.47 - - [19/Apr/2019 11:01:48] "POST /longpolling/poll HTTP/1.1" 200 -

While the process was running I checked command top, and in both cases it showed CPU for Odoo process movieng from 0,3% to 0,7%, and memory value around 4,6%. The free command showed 2,5Gb of free memory during the process.

Hope this shed some light, please let me know if I can make more tests or you want me to check any other logs.

Thank you, best regards

**Comment by Yenthe666** [comment] 2019-04-19 11:15
Can you share your Odoo configuration file please? Make sure you remove the master password though.
What are the timeouts that you have configured? What is the speed of your internet on the server?

**Comment by AntMoreno** [comment] 2019-04-19 13:08
Hi @Yenthe666, of course, here is my config file content:

_[options]
addons_path = /opt/odoo/addons_custom,/opt/odoo/addons_OCA_l10n_es,/opt/odoo/addons
admin_passwd = [removed]
auto_reload = False
csv_internal_sep = ,
data_dir = /opt/odoo/.local/share/Odoo
db_host = False
db_maxconn = 64
db_name = False
db_password = [removed]
db_port = False
db_template = template1
db_user = odoo
dbfilter = .*
debug_mode = False
demo = {}
email_from = False
geoip_database = /usr/share/GeoIP/GeoLiteCity.dat
import_partial = 
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 60
limit_time_real = 120
list_db = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
logfile = /var/log/odoo/odoo-server.log
logrotate = False
longpolling_port = 8072
max_cron_threads = 2
osv_memory_age_limit = 1.0
osv_memory_count_limit = False
pg_path = None
pidfile = False
proxy_mode = False
reportgz = False
secure_cert_file = server.cert
secure_pkey_file = server.pkey
server_wide_modules = None
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
syslog = False
test_commit = False
test_enable = False
test_file = False
test_report_directory = False
timezone = False
translate_modules = ['all']
unaccent = False
without_demo = False
workers = 0
xmlrpc = True
xmlrpc_interface = 
xmlrpc_port = 8069
xmlrpcs = True
xmlrpcs_interface = 
xmlrpcs_port = 8071_

As per the speed of the internet connection of the server I really don't know, since this is an AWS machine, is a m3.medium EC2 machine type, is all I know. RAM is 4Gb, HD is 24Gb (SSD) with 8Gb free, and OS is Ubuntu 14.4

Thank you, best regards

**Comment by Yenthe666** [comment] 2019-04-19 13:36
Hmm your CPU timeout is 60 mins and all other params are higher so I can't imagine that your backup would take longer than 60 minutes. I honestly don't see a direct issue 😕

**Comment by AntMoreno** [comment] 2019-04-21 23:02
No, backups just take a couple of minutes, 3 at most, when done via web interface.

I seem to have found a solution (at least temporary) by creating a 1Gb swap file. Backups are working again, so definitely the issue has something to do with memory. I don´'t know how long will it take to fail again, I will inform here.

Thank you, best regards

**Comment by Yenthe666** [comment] 2019-04-22 09:45
I guess your server doesn't have enough space to create the backup in memory then, resulting in a fail.
